version: '2'
services:
  bob:
    extends:
      file: docker-compose/base.yaml
      service: bob
    depends_on:
      - db
      - resource-git
      - artifact-local
    networks:
      - bob_net

  db:
    extends:
      file: docker-compose/base.yaml
      service: db
    networks:
      - bob_net

  resource-git:
    extends:
      file: docker-compose/base.yaml
      service: resource-git
    networks:
      - bob_net

  artifact-local:
    extends:
      file: docker-compose/base.yaml
      service: artifact-local
    networks:
      - bob_net
networks:
  bob_net:
